server:
  image: node
  command: npm run backend
  restart: always
  working_dir: /app
  volumes:
    - ./server:/app
  environment:
    PORT: 3000
  ports:
    - "3000:3000"
  links:
    - mongodb

frontend:
  image: node
  command: npm run webpack
  restart: always
  working_dir: /app
  volumes:
    - ./frontend:/app
  ports:
    - "4000:4000"

public:
  image: nginx
  ports:
      - "8080:8080"
  volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html

mongobrowser:
  image: mongo-express
  links:
    - mongodb:mongo
  ports:
    - "8081:8081"
  environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance" 
    # - ME_CONFIG_BASICAUTH_USERNAME="admin" 
    # - ME_CONFIG_BASICAUTH_PASSWORD="pass"

mongodb:
  image: mongo
  ports:
      - "27017:27017"

